name: Dispatch a SSH session

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Leave only desired OS in the field'
        required: true
        default: 'ubuntu-24.04'

jobs:
  start_ssh_session:
    runs-on: ${{ github.event.inputs.os }}
    name: Start the SSH session
    steps:
    - name: Start SSH session
      uses: luchihoratiu/debug-via-ssh@main
      with:
        AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        PASSWORD: ${{ secrets.PASSWORD }}
        NGROK_TIMEOUT: 2500
