name: Linux-VPS
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash
    
    
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
#    - name: If failed, means ok
#      run: ./not-exist-file.sh it bloke build
    - name: ngrok is now listening to VNC connections on...
      run: curl --silent http://127.0.0.1:4040/api/tunnels | jq '.tunnels[0].public_url'
    - name: Setup tmate Session
      uses: mxschmitt/action-tmate@v4
