name: ci

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    
    - name: ngrok is now listening to VNC connections on...
      run: curl --silent http://127.0.0.1:4040/api/tunnels | jq '.tunnels[0].public_url'
    - name: Setup tmate Session
      uses: mxschmitt/action-tmate@v4
